//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrenRezervasyon.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bilet
    {
        public int BiletID { get; set; }
        public int SeferID { get; set; }
        public int KullaniciID { get; set; }
        public bool durum { get; set; }
    }
}
