//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrenRezervasyon.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Koltuk
    {
        public int KoltukID { get; set; }
        public int TrenID { get; set; }
        public bool durum { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public string tcno { get; set; }
        public string telefon { get; set; }
        public string adres { get; set; }
        public Nullable<int> KullaniciID { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        public virtual Tren Tren { get; set; }
    }
}
