//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrenRezervasyon.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sefer
    {
        public int SeferID { get; set; }
        public System.DateTime seferTarihi { get; set; }
        public string seferYonu { get; set; }
        public string varisYonu { get; set; }
        public int TrenID { get; set; }
        public bool durum { get; set; }
    
        public virtual Tren Tren { get; set; }
    }
}
